### ISSUE TITLE
unable to fetch the stock value

### ISSUE THREAD

**Issue by kiranbakale** [elyserobinson/whatsappstockbot#1]
### _**it Shows up $None value at the price please reply at the earliest btw beautiful project**_
![IMG_20210718_151925](https://user-images.githubusercontent.com/46279617/126062856-b6733e7b-5525-44f2-81fd-f47a7932d2b8.jpg)

![InkedIMG_20210718_153532_LI](https://user-images.githubusercontent.com/46279617/126063382-3f6d620c-cb8f-4ed8-baf3-43afce767208.jpg)

**Comment by elyserobinson** [comment]
Thank you and I appreciate the love. 🤗

This isn't my original project. You can find the Udemy course here: https://www.udemy.com/course/whatsapp-stock-market-bot-with-python-twilio-marketstack
